version: '3.8'
services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      MARIADB_DATABASE: bssdb
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_USER: bssuser
    ports:
      - '0.0.0.0:3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
