spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/BankingSystemSpring
    username: bssuser
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update            # Automatic database schema generation (update, create, validate, none)
      show-sql: true              # Enable SQL logging for debugging
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    baseline-on-migrate: false
    url: jdbc:mariadb://localhost:3306/bssdb
    user: bssuser
    password: secret
    locations: classpath:db/migration
    driver-class-name: org.mariadb.jdbc.Driver
    enabled: true