spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bssdb
    username: bssuser
    password: verysecret
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update            # Automatic database schema generation (update, create, validate, none)
      show-sql: true              # Enable SQL logging for debugging
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect