spring:
 datasource:
   url: jdbc:mariadb://localhost:3306/bssdb
   username: bssuser
   password: secret
   driver-class-name: org.mariadb.jdbc.Driver
 jpa:
   hibernate:
     ddl-auto: update          # Automatic database schema generation (update, create, validate, none)
     database-platform: org.hibernate.dialect.MariaDBDialect
     properties:
       hibernate:
         dialect: org.hibernate.dialect.MariaDBDialect
         show_sql: true            # Enable SQL logging for debugging
     naming:
       implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl