name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Use Adoptium Temurin distribution
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  # Make the Gradle wrapper executable

      - name: Build with Gradle
        run: ./gradlew build -x test  # Build your project and skip tests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "build/libs/*.jar" 
          target: "/home/${{ secrets.USERNAME }}/BankingSystemSpring"

      - name: Restart Spring Boot App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo systemctl stop BankingSystemSpring.service
            sudo systemctl start BankingSystemSpring.service
